name: cicd-1
on:
  pull_request:
    types: [opened, synchronize, closed] #PR이 open되거나 동기화 될 때 CI실행
    branches: [dev]
    paths:
    - 'my-app/**'

jobs:
  test: #CI를 위해 실행되는 job 
    if: github.event.action == 'opened' || github.event.action == 'synchronize'
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

  image-build: #PR이 merge되면 실행되는 job, 즉 CD 단계에서 실행된다. 
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

  deploy: #CD단계에서 실행하는 job 
    runs-on: ubuntu-latest
    needs: [image-build] #image build job이 성공한 다음 실행되어야 한다. 
    steps:
    - name: checkout
      uses: actions/checkout@v4