name: issue-notify

on: # 트리거 구성 
  issues:  # issue가 오픈될 때 실행 
    types: [opened]

jobs:
  get-keyword:
    runs-on: ubuntu-latest
    outputs:
      level: ${{ steps.get-keyword.outputs.level }}
    steps:
    - name: checkout #github repo 코드를 github job으로 가져온다. 
      uses: actions/checkout@v4
    - name: get keyword
      id: get-keyword
      run: |
        echo level=Undefined >> $GITHUB_OUTPUT 

        keywords=$(cat keyword-list.txt)
        for keyword in $keywords; do
          if [[ "${{ github.event.issue.title }}" =~ "$keyword" ]]; then
            echo level=$keyword >> $GITHUB_OUTPUT
          fi
        done
    - name: get output
      run: |
        echo ${{ steps.get-keyword.outputs.level }}

  slack:
    needs: [get-keyword] #get-keyword job이 실행된 이후에 실행되어야 하기 때문에 needs 키워드 사용 
    if: needs.get-keyword.outputs.level != 'Undefined'
    runs-on: ubuntu-latest
    environment: ${{ needs.get-keyword.outputs.level }}
    steps:
    - name: slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        payload: |
          {
            "attachments": [
              {
                "pretext": "issue alert message",
                "color": "28a745",
                "fields": [
                  {
                    "title": "Level : ${{ needs.get-keyword.outputs.level }}",
                    "short": true,
                    "value": "issue url : ${{ github.event.issue.html_url }}"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
